one_number = int(input('Введите число: '))
two_number = int(input('Введите число: '))
three_number = int(input('Введите число: '))
four_number = int(input('Введите число: '))
print((one_number + two_number) / (three_number + four_number))